/* DO NOT EDIT. THIS FILE IS AUTOGENERATED. */
type Params = Promise<{ id: string }>;
type SearchParams = Promise<{ [key: string]: string | string[] | undefined }>;

export default async function Page(props: {
  params: Params;
  searchParams: SearchParams;
}) {
  const params = await props.params;
  const searchParams = await props.searchParams;
  return (
    <div>
      <p>params: {JSON.stringify(params)}</p>
      <p>searchParams: {JSON.stringify(searchParams)}</p>
    </div>
  );
}
